"""
Code generator for actuarial model bindings.

Reads registry.json and produces three C++ files in generated/:
  - script_contexts.h   (typed structs — one per script)
  - runtime_context.h   (thread_local pointers + RAII guards)
  - bindings.cpp        (pybind11 get_*/set_* for every variable)

The generated code is identical to what you'd write by hand in src_tls_vec.
Same structs, same field access, same performance. Zero map overhead.

Usage:
    python codegen.py
    python codegen.py --registry path/to/registry.json --outdir path/to/generated
"""

import json
import argparse
from pathlib import Path

# ── Type mappings ────────────────────────────────────────────────────

CPP_TYPES = {
    "int":    "int",
    "double": "double",
    "vector": "std::vector<double>",
}

CPP_DEFAULTS = {
    "int":    "0",
    "double": "0.0",
}


def to_pascal(name: str) -> str:
    """eia_credit -> EiaCredit"""
    return "".join(w.capitalize() for w in name.split("_"))


def generate_script_contexts(scripts: list) -> str:
    """Generate script_contexts.h — one typed struct per script."""
    lines = [
        "// AUTO-GENERATED by codegen.py — do not edit by hand.",
        "// Source: registry.json",
        "#pragma once",
        "#include <vector>",
        "",
    ]

    for script in scripts:
        struct_name = f"{to_pascal(script['name'])}Context"
        lines.append(f"struct {struct_name} {{")

        # Inputs
        inputs = [v for v in script["vars"] if v["direction"] == "input"]
        if inputs:
            lines.append("    // READ-ONLY inputs (set by C++ before calling the script)")
        for var in inputs:
            cpp_type = CPP_TYPES[var["type"]]
            default = CPP_DEFAULTS.get(var["type"], "")
            if default:
                lines.append(f"    {cpp_type:30s} {var['name']} = {default};")
            else:
                lines.append(f"    {cpp_type:30s} {var['name']};")

        # Outputs
        outputs = [v for v in script["vars"] if v["direction"] == "output"]
        if outputs:
            lines.append("")
            lines.append("    // WRITE-ONLY outputs (filled by Python — one value per month)")
        for var in outputs:
            cpp_type = CPP_TYPES[var["type"]]
            lines.append(f"    {cpp_type:30s} {var['name']};")

        lines.append("};")
        lines.append("")

    return "\n".join(lines)


def generate_runtime_context(scripts: list) -> str:
    """Generate runtime_context.h — thread_local pointers + guards."""
    lines = [
        "// AUTO-GENERATED by codegen.py — do not edit by hand.",
        "// Source: registry.json",
        "#pragma once",
        "#include \"script_contexts.h\"",
        "#include <stdexcept>",
        "",
        "// ── Thread-local active context pointers ─────────────────────────",
    ]

    # Thread-local pointers
    for script in scripts:
        struct_name = f"{to_pascal(script['name'])}Context"
        tls_var = f"g_{script['name']}_ctx"
        lines.append(f"inline thread_local {struct_name}* {tls_var} = nullptr;")

    lines.append("")
    lines.append("// ── RAII guards ─────────────────────────────────────────────────")

    # Guard classes
    for script in scripts:
        struct_name = f"{to_pascal(script['name'])}Context"
        guard_name = f"{to_pascal(script['name'])}Guard"
        tls_var = f"g_{script['name']}_ctx"
        lines.extend([
            f"struct {guard_name} {{",
            f"    {guard_name}({struct_name}& ctx) {{ {tls_var} = &ctx; }}",
            f"    ~{guard_name}() {{ {tls_var} = nullptr; }}",
            f"    {guard_name}(const {guard_name}&) = delete;",
            f"    {guard_name}& operator=(const {guard_name}&) = delete;",
            f"}};",
            "",
        ])

    lines.append("// ── Active context accessors ───────────────────────────────────")

    # Active accessor functions
    for script in scripts:
        struct_name = f"{to_pascal(script['name'])}Context"
        fn_name = f"active_{script['name']}"
        tls_var = f"g_{script['name']}_ctx"
        lines.extend([
            f"inline {struct_name}& {fn_name}() {{",
            f"    if (!{tls_var})",
            f"        throw std::runtime_error(\"No active {script['name']} context\");",
            f"    return *{tls_var};",
            f"}}",
            "",
        ])

    return "\n".join(lines)


def generate_bindings(scripts: list) -> str:
    """Generate bindings.cpp — pybind11 submodules with get_*/set_*."""
    lines = [
        "// AUTO-GENERATED by codegen.py — do not edit by hand.",
        "// Source: registry.json",
        "#include <pybind11/embed.h>",
        "#include <pybind11/stl.h>",
        "#include \"runtime_context.h\"",
        "",
        "namespace py = pybind11;",
        "",
        "PYBIND11_EMBEDDED_MODULE(actuarial, m) {",
        '    m.doc() = "Actuarial projection library — code-generated bindings";',
        "",
    ]

    for script in scripts:
        fn_name = f"active_{script['name']}"
        sub_var = script["name"].replace("_", "")
        lines.append(f'    auto {sub_var} = m.def_submodule("{script["name"]}");')

        for var in script["vars"]:
            vname = var["name"]
            vtype = var["type"]

            if var["direction"] == "input":
                if vtype == "vector":
                    lines.extend([
                        f'    {sub_var}.def("get_{vname}",',
                        f'        []() -> const std::vector<double>& {{ return {fn_name}().{vname}; }},',
                        f'        py::return_value_policy::reference);',
                    ])
                else:
                    lines.extend([
                        f'    {sub_var}.def("get_{vname}",',
                        f'        []() {{ return {fn_name}().{vname}; }});',
                    ])
            else:
                if vtype == "vector":
                    lines.extend([
                        f'    {sub_var}.def("set_{vname}",',
                        f'        [](std::vector<double> v) {{ {fn_name}().{vname} = std::move(v); }},',
                        f'        py::arg("rates"));',
                    ])
                elif vtype == "double":
                    lines.extend([
                        f'    {sub_var}.def("set_{vname}",',
                        f'        [](double v) {{ {fn_name}().{vname} = v; }},',
                        f'        py::arg("value"));',
                    ])
                else:
                    lines.extend([
                        f'    {sub_var}.def("set_{vname}",',
                        f'        [](int v) {{ {fn_name}().{vname} = v; }},',
                        f'        py::arg("value"));',
                    ])

        lines.append("")

    lines.append("}")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate C++ from registry.json")
    parser.add_argument("--registry", default=None,
                        help="Path to registry.json")
    parser.add_argument("--outdir", default=None,
                        help="Output directory for generated files")
    args = parser.parse_args()

    # Default paths relative to this script's location
    script_dir = Path(__file__).parent
    registry_path = Path(args.registry) if args.registry else script_dir / "registry.json"
    out_dir = Path(args.outdir) if args.outdir else script_dir / "generated"

    out_dir.mkdir(parents=True, exist_ok=True)

    with open(registry_path) as f:
        registry = json.load(f)

    scripts = registry["scripts"]

    files = {
        "script_contexts.h": generate_script_contexts(scripts),
        "runtime_context.h": generate_runtime_context(scripts),
        "bindings.cpp":      generate_bindings(scripts),
    }

    for filename, content in files.items():
        path = out_dir / filename
        path.write_text(content + "\n", encoding="utf-8")
        print(f"  Generated {path}")


if __name__ == "__main__":
    main()
